[build]
    base = "frontend"
    publish = ".next"
    command = "rm -rf node_modules .next && bun install && bun run build"

[[plugins]]
    package = "@netlify/plugin-nextjs"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

